countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
    "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
    "Jamaica", "Japan", "Jordan",
    "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway",
    "Oman",
    "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar",
    "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
    "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
    "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
    "Yemen",
    "Zambia", "Zimbabwe"
]

cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Washington",
    "Boston", "El Paso", "Nashville", "Detroit", "Portland", "Memphis", "Oklahoma City", "Las Vegas", "Louisville", "Baltimore",
    "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa", "Atlanta", "Kansas City", "Colorado Springs", "Omaha",
    "Raleigh", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa", "Wichita", "New Orleans", "Arlington",
    "Cleveland", "Bakersfield", "Tampa", "Aurora", "Honolulu", "Anaheim", "Santa Ana", "St. Louis", "Riverside", "Corpus Christi",
    "Lexington", "Pittsburgh", "Anchorage", "Stockton", "Cincinnati", "St. Paul", "Toledo", "Greensboro", "Newark", "Plano",
    "Henderson", "Lincoln", "Orlando", "Jersey City", "Chandler", "Laredo", "Madison", "Durham", "Buffalo", "Lubbock", "Winston-Salem",
    "Glendale", "Reno", "Baton Rouge", "Chesapeake", "Irving", "Scottsdale", "North Las Vegas", "Fremont", "Gilbert", "San Bernardino",
    "Boise", "Birmingham", "Richmond", "Spokane", "Des Moines", "Rochester", "Modesto", "Fayetteville", "Tacoma", "Oxnard",
    "Fontana", "Columbus", "Montgomery", "Moreno Valley", "Shreveport", "Aurora", "Yonkers", "Akron", "Huntington Beach", "Little Rock",
    "Augusta", "Amarillo", "Glendale", "Mobile", "Grand Rapids", "Salt Lake City", "Tallahassee", "Huntsville", "Knoxville", "Worcester",
    "Newport News", "Brownsville", "Overland Park", "Santa Clarita", "Providence", "Garden Grove", "Chattanooga", "Oceanside", "Jackson",
    "Fort Lauderdale", "Santa Rosa", "Rancho Cucamonga", "Port St. Lucie", "Tempe", "Ontario", "Vancouver", "Cape Coral", "Sioux Falls",
    "Springfield", "Peoria", "Pembroke Pines", "Elk Grove", "Salem", "Lancaster", "Corona", "Eugene", "Palmdale", "Salinas",
    "Springfield", "Pasadena", "Fort Collins", "Hayward", "Pomona", "Cary", "Rockford", "Alexandria", "Escondido", "McKinney",
    "Kansas City", "Joliet", "Sunnyvale", "Torrance", "Bridgeport", "Lakewood", "Hollywood", "Paterson", "Naperville", "Syracuse",
    "Mesquite", "Dayton", "Savannah", "Clarksville", "Orange", "Pasadena", "Fullerton", "Killeen", "Frisco", "Hampton",
    "McAllen", "Warren", "Bellevue", "West Valley City", "Columbia", "Olathe", "Sterling Heights", "New Haven", "Miramar", "Waco",
    "Thousand Oaks", "Cedar Rapids", "Charleston", "Visalia", "Topeka", "Elizabeth", "Gainesville", "Thornton", "Roseville", "Carrollton",
    "Coral Springs", "Stamford", "Hartford", "Concord", "Kent", "Santa Clara", "Elizabeth", "Round Rock", "Thousand Oaks", "Lafayette",
    "Athens", "Topeka", "Simi Valley", "Fargo", "Norman", "Abilene", "Columbia", "Pearland", "Victorville", "Evansville", "Vallejo",
    "Independence", "College Station", "Berkeley", "Peoria", "Inglewood", "Springfield", "West Covina", "Ann Arbor", "Miami Gardens", "Elkhart",
    "Downey", "Utica", "Lansing", "Costa Mesa", "Miami Beach", "Jurupa Valley", "Waterbury", "Provo", "Boise", "Santa Maria", "Murfreesboro",
    "El Monte", "Midland", "Wilmington", "Westminster", "Rochester", "Odessa", "Manchester", "Clearwater", "West Jordan", "Pueblo",
    "Lowell", "Arvada", "Ventura", "Westminster", "North Charleston", "San Buenaventura", "Fairfield", "Everett", "Manchester", "Carlsbad",
    "Palm Bay", "Antioch", "Daly City", "Merced", "West Allis", "Norwich", "San Mateo", "Wilmington", "Renton", "Burbank", "Erie",
    "Revere", "Pflugerville", "Greenwood", "South Gate", "Carrollton", "Plainfield", "Grand Prairie", "New Bedford", "North Little Rock", "Mansfield",
    "Brockton", "Auburn", "Albany", "Decatur", "San Ramon", "Pleasanton", "Wyoming", "Lake Charles", "Petaluma", "West Haven", "Santa Cruz",
    "Homestead", "Bryan", "Midwest City", "Fountain Valley", "Boulder", "St. Clair Shores", "Alameda", "Longview", "La Habra", "Laguna Niguel",
    "Kenner", "Walnut Creek", "Frederick", "Oshkosh", "Pittsburg", "Meridian", "Rockville", "Gulfport", "Vincent", "Milpitas", "Troy",
    "Madera", "Bedford", "East Los Angeles", "Glendora", "Burnsville", "Palatine", "Sanford", "Florissant", "Hammond", "Bolingbrook", "Gary",
    "Alhambra", "Napa", "Arlington Heights", "Chicago"
]

male_names = [
    "James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Charles",
    "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
    "Kenneth", "Kevin", "Brian", "George", "Edward", "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan",
    "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon",
    "Benjamin", "Samuel", "Frank", "Gregory", "Raymond", "Alexander", "Patrick", "Jack", "Dennis", "Jerry",
    "Tyler", "Aaron", "Jose", "Adam", "Henry", "Nathan", "Douglas", "Zachary", "Peter", "Kyle", "Walter",
    "Ethan", "Jeremy", "Harold", "Keith", "Christian", "Roger", "Noah", "Gerald", "Carl", "Terry", "Sean",
    "Austin", "Arthur", "Lawrence", "Jesse", "Dylan", "Bryan", "Joe", "Jordan", "Billy", "Albert", "Bruce",
    "Willie", "Gabriel", "Logan", "Alan", "Juan", "Wayne", "Roy", "Ralph", "Randy", "Eugene", "Vincent",
    "Russell", "Elijah", "Louis", "Bobby", "Philip", "Johnny", "Howard", "Fred", "Martin", "Dale", "Mason",
    "Derek", "Randall", "Shawn", "Devin", "Travis", "Bradley", "Joel", "Edwin", "Eddie", "Barry", "Oscar",
    "Dustin", "Marvin", "Caleb", "Manuel", "Theodore", "Clifford", "Miguel", "Glenn", "Jared", "Lucas", "Jeremiah",
    "Evan", "Julian", "Angel", "Isaiah", "Connor", "Gavin", "Charles", "Adrian", "Cameron", "Liam", "Owen",
    "Cody", "Colin", "Dominic", "Hunter", "Justin", "Seth", "Chase", "Xavier", "Leo", "Julius", "Carter",
    "Wyatt", "Damian", "Henry", "Hector", "Marcus", "Tristan", "Eli", "Micah", "Max", "Neil", "Ricky",
    "Steve", "Trevor", "Victor", "Derrick", "Damon", "Geoffrey", "Warren", "Clayton", "Maurice", "Malcolm", "Clinton"
]

female_names = [
    "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen",
    "Nancy", "Lisa", "Margaret", "Betty", "Dorothy", "Sandra", "Ashley", "Kimberly", "Donna", "Emily",
    "Michelle", "Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Laura", "Sharon", "Cynthia",
    "Kathleen", "Helen", "Amy", "Anna", "Shirley", "Angela", "Ruth", "Brenda", "Pamela", "Nicole", "Katherine",
    "Samantha", "Christine", "Catherine", "Virginia", "Debra", "Rachel", "Carolyn", "Janet", "Maria", "Heather",
    "Diane", "Julie", "Joyce", "Emma", "Frances", "Evelyn", "Joan", "Christina", "Kelly", "Victoria", "Lauren",
    "Martha", "Judith", "Cheryl", "Megan", "Andrea", "Ann", "Alice", "Jean", "Doris", "Kathryn", "Gloria",
    "Teresa", "Hannah", "Olivia", "Marie", "Jacqueline", "Sara", "Janice", "Grace", "Rose", "Julia", "Theresa",
    "Judy", "Beverly", "Denise", "Marilyn", "Amber", "Danielle", "Brittany", "Diana", "Jane", "Lori", "Madison",
    "Tiffany", "Kathy", "Tammy", "Crystal", "Natalie", "Abigail", "Renee", "Lillian", "Ella", "Stacy", "Cindy",
    "Ellen", "Wanda", "Phyllis", "Sheila", "Gail", "Carla", "Yvonne", "Sylvia", "Josephine", "Elaine", "Charlotte",
    "Monica", "Tina", "Bernice", "Tracey", "Rita", "Rebecca", "Dawn", "Connie", "Fiona", "Leah", "Erin", "Veronica",
    "Jill", "Erica", "Paula", "Darlene", "Vivian", "Roberta", "Holly", "Sylvia", "Katrina", "Molly", "Charlene",
    "Sheri", "Kara", "Jenny", "Allison", "Tamara", "Bonnie", "Julia", "Kristen", "Sherry", "Maureen", "Claudia",
    "Stacey", "Deanna", "Hope", "Alexis", "Tara", "Kayla", "Ana", "Kristin", "Alison", "Miranda", "Marissa", "Savannah"
]

surnames = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
    "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams", "Nelson",
    "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner",
    "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers",
    "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox",
    "Ward", "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennet", "Gray", "Mendoza", "Ruiz", "Hughes",
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster", "Jimenez", "Powell", "Jenkins",
    "Perry", "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", "Gonzales", "Fisher", "Vasquez",
    "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton", "Graham", "Reynolds", "Griffin", "Wallace", "Moreno",
    "West", "Cole", "Hayes", "Bryant", "Herrera", "Gibson", "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray", "Ford",
    "Castro", "Marshall", "Owens", "Harrison", "Fernandez", "Mcdonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas",
    "Henry", "Chen", "Freeman", "Webb", "Tucker", "Guzman", "Burns", "Crawford", "Olson", "Simpson", "Porter", "Hunter", "Gordon",
    "Mendez", "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks", "Holmes", "Palmer", "Wagner", "Black", "Robertson",
    "Boyd", "Rose", "Stone", "Salazar", "Fox", "Warren", "Mills", "Meyer", "Rice", "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols",
    "Stephens", "Bryant", "Chavez", "Bowman", "Davidson", "May", "Day", "Schneider", "Newman", "Brewer", "Lucas", "Holland", "Wong", "Banks",
    "Santos", "Curtis", "Pearson", "Delgado", "Valdez", "Pena", "Rios", "Douglas", "Sandoval", "Barrett", "Hopkins", "Keller", "Guerrero", "Stanley",
    "Bates", "Alvarado", "Beck", "Ortega", "Wade", "Estrada", "Contreras", "Barnett", "Caldwell", "Santiago", "Lambert", "Powers", "Chambers", "Nunez",
    "Craig", "Leonard", "Lowe", "Rhodes", "Byrd", "Gregory", "Shelton", "Frazier", "Becker", "Maldonado", "Fleming", "Vega", "Sutton", "Cohen", "Jennings",
    "Parks", "Mcdaniel", "Watts", "Barker", "Norris", "Vaughn", "Vazquez", "Holt", "Schwartz", "Steele", "Benson", "Neal", "Dominguez", "Horton", "Terry",
    "Wolfe", "Hale", "Lyons", "Graves", "Haynes", "Miles", "Park", "Warner", "Padilla", "Bush", "Thornton", "Mccarthy", "Mann", "Zimmerman", "Erickson", "Fletcher",
    "Mckinney", "Page", "Dawson", "Joseph", "Marquez", "Reeves", "Klein", "Espinoza", "Baldwin", "Moran", "Love", "Robbins", "Higgins", "Ball", "Cortez", "Le", "Griffith",
    "Bowen", "Sharp", "Cummings", "Ramsey", "Hardy", "Swanson", "Barber", "Acosta", "Luna", "Chandler", "Blair", "Daniel", "Cross", "Simon", "Dennis", "Oconnor", "Quinn", "Gross",
    "Navarro", "Moss", "Fitzgerald", "Doyle", "Mclaughlin", "Rojas", "Rodgers", "Stevenson", "Singh", "Yang", "Figueroa", "Harmon", "Newton", "Paul", "Manning", "Garner", "Mcgee", "Reese",
    "Francis", "Burgess", "Adkins", "Goodman", "Curry", "Brady", "Christensen", "Potter", "Walton", "Goodwin", "Mullins", "Molina", "Webster", "Fischer", "Campos", "Avila", "Sherman", "Todd",
    "Chang", "Blake", "Malone", "Wolf", "Hodges", "Juarez", "Gill", "Farmer", "Hines", "Gallagher", "Duran", "Hubbard", "Cannon", "Miranda", "Wang", "Saunders", "Tate", "Mack", "Hammond", "Carrillo",
    "Townsend", "Wise", "Ingram", "Barton", "Mejia", "Ayala", "Schroeder", "Hampton", "Rowe", "Parsons", "Frank", "Waters", "Strickland", "Osborne", "Maxwell", "Chan", "Deleon", "Norman", "Harrington", "Casey",
    "Patton", "Logan", "Bowers", "Mueller", "Glover", "Floyd", "Hartman", "Buchanan", "Cobb", "French", "Kramer", "Mccormick", "Clarke", "Tyler", "Gibbs", "Moody", "Conner", "Sparks", "Mcguire", "Leon", "Bauer",
    "Norton", "Pope", "Flynn", "Hogan", "Robles", "Salinas", "Yates", "Lindsey", "Lloyd", "Marsh", "Mcbride", "Owen", "Solis", "Pham", "Lang", "Pratt", "Lara", "Brock", "Ballard", "Trujillo", "Shaffer", "Drake", "Roman",
    "Aguirre", "Morton", "Stokes", "Lamb", "Pacheco", "Patrick", "Cochran", "Shepherd", "Cain", "Burnett", "Hess", "Li", "Cervantes", "Olsen", "Briggs", "Ochoa", "Cabrera", "Velasquez", "Montoya", "Roth", "Meyers", "Cardenas",
    "Fuentes", "Weiss", "Hoover", "Wilkins", "Nicholson", "Underwood", "Short", "Carson", "Morrow", "Colon", "Holloway", "Summers", "Bryan", "Petersen", "Mckenzie", "Serrano", "Wilcox", "Carey", "Clayton", "Poole", "Calderon", "Gallegos",
    "Greer", "Rivas", "Guerra", "Decker", "Collier", "Wall", "Whitaker", "Bass", "Flowers", "Davenport", "Conley", "Houston", "Huff", "Copeland", "Hood", "Monroe", "Massey", "Roberson", "Combs", "Franco", "Larsen", "Pittman", "Randall", "Skinner",
    "Wilkinson", "Kirby", "Cameron", "Bridges", "Anthony", "Richard", "Kirk", "Bruce", "Singleton", "Mathias", "Bradford", "Boone", "Abbott", "Charles", "Allison", "Sweeney", "Atkinson", "Horn", "Jefferson", "Rosales", "York", "Christian", "Phelps",
    "Farrell", "Castaneda", "Nash", "Dickerson", "Bond", "Wyatt", "Foley", "Chase", "Gates", "Vincent", "Mathews", "Hodge", "Garrison", "Trevino", "Villarreal", "Heath", "Dalton", "Valencia", "Callahan", "Hensley", "Atkins", "Huffman", "Roy", "Boyer",
    "Shields", "Lin", "Hancock", "Grimes", "Glenn", "Cline", "Delacruz", "Camacho", "Dillon", "Parrish", "Oneill", "Melton", "Booth", "Kane", "Berg", "Harrell", "Pitts", "Savage", "Wiggins", "Brennan", "Salas", "Marks", "Russo", "Sawyer", "Baxter", "Golden",
    "Hutchinson", "Liu", "Walter", "Mcdowell", "Wiley", "Rich", "Humphrey", "Johns", "Koch", "Suarez", "Hobbs", "Beard", "Gilmore", "Ibarra", "Keith", "Macias", "Khan", "Andrade", "Ware", "Stephenson", "Henson", "Wilkerson", "Dyer", "Mcclure", "Blackwell", "Mercado",
    "Tanner", "Eaton", "Clay", "Barron", "Beasley", "Oneal", "Preston", "Small", "Wu", "Zamora", "Macdonald", "Vance", "Snow", "Mcclain", "Stafford", "Orozco", "Barry", "English", "Shannon", "Kline", "Jacobson", "Woodard", "Huang", "Kemp", "Mosley", "Prince", "Merritt", "Hurst",
    "Villanueva", "Roach", "Nolan", "Lam", "Yoder", "McCray", "Schaefer", "Strong", "Ortiz", "Barr", "David", "Dejesus", "Marin", "Berger", "Mckee", "Bishop", "Fritz", "Archer", "Sloan", "Rooney", "Moon", "Sanders", "Barrera", "Leach", "Orr", "Bergman", "Burch"
]

organizations = [
    "Apple", "Microsoft", "Google", "Amazon", "Facebook", "Tesla", "IBM", "Intel", "Oracle", "Samsung",
    "Sony", "Nike", "Adidas", "Coca-Cola", "Pepsi", "McDonald's", "Starbucks", "Walmart", "Target", "Costco",
    "General Electric", "General Motors", "Ford", "Toyota", "Volkswagen", "BMW", "Mercedes-Benz", "Audi", "Honda",
    "Nissan", "Dell", "HP", "Lenovo", "Asus", "Acer", "Canon", "Nikon", "Sony", "Panasonic",
    "LG", "Philips", "Bosch", "Siemens", "SAP", "Adobe", "Autodesk", "Salesforce", "Slack", "Zoom",
    "Netflix", "Disney", "Warner Bros", "Universal", "Paramount", "20th Century Fox", "DreamWorks", "Pixar", "Marvel",
    "DC Comics", "NBC", "CBS", "ABC", "Fox", "CNN", "BBC", "Al Jazeera", "Reuters", "Associated Press",
    "The New York Times", "The Washington Post", "The Guardian", "The Wall Street Journal", "Bloomberg", "Forbes", "Time", "National Geographic",
    "United Nations", "World Health Organization", "Red Cross", "Amnesty International", "Greenpeace", "UNICEF", "Save the Children", "Doctors Without Borders",
    "Harvard University", "Stanford University", "MIT", "Oxford University", "Cambridge University", "Yale University", "Princeton University", "Columbia University",
    "University of Chicago", "University of California", "University of Texas", "University of Michigan", "University of Pennsylvania", "Cornell University", "Duke University",
    "Cisco", "Qualcomm", "AMD", "NVIDIA", "Dropbox", "Spotify", "Twitter", "Snapchat", "TikTok", "Instagram",
    "LinkedIn", "Airbnb", "Uber", "Lyft", "DoorDash", "Grubhub", "Yelp", "TripAdvisor", "Expedia", "Booking.com",
    "American Express", "Visa", "MasterCard", "PayPal", "Stripe", "Square", "Chase", "Bank of America", "Wells Fargo",
    "Citibank", "Goldman Sachs", "JPMorgan Chase", "Morgan Stanley", "Barclays", "HSBC", "Deutsche Bank", "UBS", "Credit Suisse",
    "Airbus", "Boeing", "Lockheed Martin", "Raytheon", "Northrop Grumman", "General Dynamics", "BAE Systems", "Rolls-Royce", "Honeywell",
    "SpaceX", "Blue Origin", "Virgin Galactic", "NASA", "ESA", "CERN", "WHO", "UNESCO", "WTO", "IMF",
    "World Bank", "OECD", "Interpol", "FBI", "CIA", "NSA", "NASA", "DARPA", "RAND Corporation", "Brookings Institution",
    "Heritage Foundation", "Koch Industries", "ExxonMobil", "Chevron", "BP", "Shell", "Total", "Eni", "Equinor",
    "Saudi Aramco", "PetroChina", "Rosneft", "Gazprom", "BHP", "Rio Tinto", "Vale", "Glencore", "ArcelorMittal",
    "Tencent", "Alibaba", "Baidu", "JD.com", "ByteDance", "Huawei", "ZTE", "Xiaomi", "Oppo", "Vivo",
    "Nokia", "Ericsson", "Telefonica", "Vodafone", "Deutsche Telekom", "Orange", "BT Group", "AT&T", "Verizon",
    "Comcast", "Charter Communications", "DISH Network", "T-Mobile", "Sprint", "Bell Canada", "Rogers Communications", "Telus", "Shaw Communications",
    "Telstra", "Singtel", "SoftBank", "NTT", "KDDI", "SK Telecom", "KT", "LGU+", "China Mobile",
    "China Telecom", "China Unicom", "Reliance Jio", "Airtel", "Vodafone Idea", "Bharti Airtel", "MTN Group", "Safaricom", "Etisalat",
    "Turkcell", "Ooredoo", "STC", "Zain", "Du", "Virgin Media", "TalkTalk", "Sky", "BT",
    "EE", "Three", "O2", "Lebara", "Lycamobile", "Giffgaff", "ASDA", "Morrisons", "Sainsbury's",
    "Tesco", "Aldi", "Lidl", "Waitrose", "Marks & Spencer", "John Lewis", "Argos", "Currys", "PC World",
    "Dixons Carphone", "Boots", "Superdrug", "Holland & Barrett", "Poundland", "Home Bargains", "B&M", "Wilko", "The Range",
    "Next", "Primark", "River Island", "New Look", "Topshop", "Missguided", "PrettyLittleThing", "Boohoo", "ASOS",
    "Zara", "H&M", "Uniqlo", "Gap", "Levi's", "Calvin Klein", "Tommy Hilfiger", "Ralph Lauren", "Gucci",
    "Louis Vuitton", "Chanel", "Prada", "Dior", "Hermès", "Burberry", "Rolex", "Cartier", "Tiffany & Co.",
    "Starbucks", "Costa Coffee", "Caffè Nero", "Pret A Manger", "Tim Hortons", "Dunkin'", "Subway", "KFC", "Burger King",
    "Wendy's", "Chipotle", "Panda Express", "Domino's Pizza", "Papa John's", "Pizza Hut", "Little Caesars", "Jimmy John's", "Five Guys",
    "In-N-Out Burger", "Shake Shack", "Chick-fil-A", "Raising Cane's", "Whataburger", "Sonic Drive-In", "Arby's", "Hardee's", "Carl's Jr.",
    "Panera Bread", "Au Bon Pain", "Einstein Bros. Bagels", "Dunkin' Donuts", "Baskin-Robbins", "Cold Stone Creamery", "Ben & Jerry's", "Haagen-Dazs",
    "Dairy Queen", "Breyers", "Blue Bell Creameries", "Tillamook", "Talenti", "Magnum", "Klondike", "Popsicle", "Good Humor",
    "Nestle", "Unilever", "Procter & Gamble", "Johnson & Johnson", "Colgate-Palmolive", "Kimberly-Clark", "Reckitt Benckiser", "L'Oréal", "Estée Lauder",
    "Avon", "Revlon", "Coty", "Shiseido", "Kao", "Henkel", "Beiersdorf", "Church & Dwight", "Clorox", "SC Johnson",
    "P&G", "General Mills", "Kellogg's", "Nabisco", "Mondelez", "Mars", "Wrigley", "Hershey", "Ferrero", "Cadbury",
    "Lindt", "Godiva", "Russell Stover", "See's Candies", "Haribo", "Perfetti Van Melle", "Tootsie Roll", "Bazooka", "Swiss Miss",
    "Quaker Oats", "Post Holdings", "Kashi", "Nature's Bounty", "GNC", "Vitamin Shoppe", "Herbalife", "Amway", "Nu Skin",
    "Mary Kay", "Avon", "Tupperware", "Pampered Chef", "Rodan + Fields", "Younique", "Arbonne", "Isagenix", "Forever Living",
    "Primerica", "Aflac", "MetLife", "Prudential", "AIG", "Allstate", "Liberty Mutual", "State Farm", "Geico", "Progressive",
    "Nationwide", "Farmers Insurance", "USAA", "Travelers", "Chubb", "AXA", "Allianz", "Munich Re", "Swiss Re", "Berkshire Hathaway",
    "BlackRock", "Vanguard", "Fidelity Investments", "Charles Schwab", "TD Ameritrade", "E*TRADE", "Robinhood", "Wealthfront", "Betterment", "Acorns",
    "SoFi", "LendingClub", "Upstart", "OnDeck", "Kabbage", "Square Financial Services", "Brex", "Stripe", "Adyen", "Klarna",
    "Affirm", "Afterpay", "Sezzle", "Zip", "Quadpay", "Splitit", "Payoneer", "WorldRemit", "TransferWise", "Remitly",
    "Western Union", "MoneyGram", "Ria Money Transfer", "Xoom", "OFX", "Currencies Direct", "TorFX", "FairFX", "Revolut",
    "N26", "Monzo", "Starling Bank", "Chase", "Bank of America", "Wells Fargo", "Citibank", "Goldman Sachs", "JPMorgan Chase",
    "Morgan Stanley", "Barclays", "HSBC", "Deutsche Bank", "UBS", "Credit Suisse", "BNP Paribas", "Société Générale", "Crédit Agricole",
    "ING Group", "ABN AMRO", "Rabobank", "Santander", "BBVA", "CaixaBank", "Banco Sabadell", "Banco Santander", "BBVA", "CaixaBank",
    "Banco Sabadell", "Banco Popular", "Banco de Sabadell", "Banco de España", "Banco de Portugal", "Banco de France", "Banco de Italia", "Banco de Alemania",
    "Banco de Suiza", "Banco de Austria", "Banco de Holanda", "Banco de Bélgica", "Banco de Luxemburgo", "Banco de Irlanda", "Banco de Noruega", "Banco de Dinamarca",
    "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia",
    "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia",
    "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa",
    "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia",
    "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa",
    "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia",
    "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia",
    "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca",
    "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia",
    "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría",
    "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia",
    "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia",
    "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia",
    "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia",
    "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania", "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega",
    "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria", "Banco de Rumanía", "Banco de Serbia", "Banco de Chipre", "Banco de Malta", "Banco de Lituania",
    "Banco de Letonia", "Banco de Estonia", "Banco de Islandia", "Banco de Noruega", "Banco de Dinamarca", "Banco de Suecia", "Banco de Finlandia", "Banco de Grecia", "Banco de Polonia", "Banco de Hungría", "Banco de República Checa", "Banco de Eslovaquia", "Banco de Eslovenia", "Banco de Croacia", "Banco de Bulgaria"]
